-- One-time seed of activities table from activities.json (81 rows).
-- Run once in the Supabase SQL editor.

INSERT INTO activities (name, places_query, places_type, budget, physical_intensity, competitiveness, group_size, outdoor, duration, novelty) VALUES
  ('Hiking', 'hiking trails', 'park', 1, 4, 1, 3, 5, 4, 1),
  ('Rock Climbing (Outdoor)', 'outdoor rock climbing', 'park', 2, 5, 2, 2, 5, 4, 3),
  ('Kayaking', 'kayak rental', NULL, 3, 3, 1, 2, 5, 3, 3),
  ('Beach Day', 'beach', 'natural_feature', 1, 2, 1, 4, 5, 5, 1),
  ('Disc Golf', 'disc golf course', 'park', 1, 3, 3, 3, 5, 3, 2),
  ('Picnic in the Park', 'park picnic area', 'park', 1, 1, 1, 3, 5, 3, 1),
  ('Cycling', 'bike trail', 'park', 1, 4, 2, 3, 5, 3, 1),
  ('Stargazing', 'stargazing spot', 'park', 1, 1, 1, 2, 5, 3, 3),
  ('Camping', 'campground', 'campground', 2, 3, 1, 3, 5, 5, 2),
  ('Paddleboarding', 'paddleboard rental', NULL, 3, 3, 1, 2, 5, 2, 3),
  ('Bowling', 'bowling alley', 'bowling_alley', 2, 2, 3, 3, 1, 2, 1),
  ('Mini Golf', 'mini golf', NULL, 2, 1, 3, 3, 3, 2, 1),
  ('Go-Kart Racing', 'go kart racing', NULL, 3, 2, 4, 3, 3, 2, 3),
  ('Laser Tag', 'laser tag', NULL, 2, 3, 4, 4, 1, 1, 2),
  ('Rock Climbing (Indoor)', 'indoor rock climbing gym', 'gym', 3, 5, 2, 2, 1, 3, 3),
  ('Paintball', 'paintball', NULL, 3, 4, 5, 4, 4, 3, 3),
  ('Trampoline Park', 'trampoline park', NULL, 2, 4, 2, 3, 1, 2, 2),
  ('Axe Throwing', 'axe throwing', NULL, 3, 2, 3, 3, 1, 2, 4),
  ('Archery', 'archery range', NULL, 2, 2, 3, 2, 2, 2, 3),
  ('Ice Skating', 'ice skating rink', NULL, 2, 3, 1, 3, 2, 2, 2),
  ('Roller Skating', 'roller skating rink', NULL, 2, 3, 1, 3, 1, 2, 2),
  ('Batting Cages', 'batting cages', NULL, 2, 3, 3, 2, 3, 1, 2),
  ('Tennis', 'tennis courts', NULL, 1, 4, 4, 2, 4, 2, 1),
  ('Volleyball', 'volleyball court', NULL, 1, 4, 4, 5, 4, 2, 1),
  ('Basketball', 'basketball court', NULL, 1, 5, 4, 4, 4, 2, 1),
  ('Escape Room', 'escape room', NULL, 3, 1, 2, 3, 1, 2, 3),
  ('Movie Theater', 'movie theater', 'movie_theater', 2, 1, 1, 3, 1, 3, 1),
  ('Trivia Night', 'bar trivia night', 'bar', 2, 1, 3, 4, 1, 3, 2),
  ('Karaoke', 'karaoke bar', 'bar', 2, 1, 2, 4, 1, 3, 2),
  ('Comedy Club', 'comedy club', 'night_club', 3, 1, 1, 3, 1, 2, 2),
  ('Live Music / Concert', 'live music venue', 'night_club', 3, 1, 1, 4, 3, 3, 2),
  ('Theater / Play', 'theater', NULL, 3, 1, 1, 3, 1, 3, 2),
  ('Haunted House', 'haunted house attraction', 'amusement_park', 3, 2, 1, 3, 2, 2, 4),
  ('Pottery Class', 'pottery class', NULL, 3, 1, 1, 2, 1, 3, 3),
  ('Sip and Paint', 'sip and paint class', NULL, 3, 1, 1, 4, 1, 3, 2),
  ('Cooking Class', 'cooking class', NULL, 4, 1, 1, 3, 1, 3, 3),
  ('Glassblowing Class', 'glassblowing class', NULL, 4, 2, 1, 2, 1, 2, 5),
  ('Photography Walk', 'photography tour', NULL, 1, 2, 1, 2, 4, 3, 3),
  ('Craft Workshop', 'craft workshop', NULL, 3, 1, 1, 3, 1, 3, 3),
  ('Candle Making Class', 'candle making class', NULL, 3, 1, 1, 3, 1, 2, 4),
  ('Wine Tasting', 'wine tasting', NULL, 3, 1, 1, 3, 2, 2, 2),
  ('Brewery Tour', 'brewery tour', NULL, 3, 1, 1, 4, 2, 2, 2),
  ('Food Tour', 'food tour', NULL, 4, 2, 1, 3, 4, 3, 3),
  ('Cocktail Making Class', 'cocktail making class mixology', 'bar', 4, 1, 1, 3, 1, 2, 3),
  ('Coffee Tasting', 'coffee tasting specialty coffee', 'cafe', 2, 1, 1, 2, 1, 1, 3),
  ('Museum Visit', 'museum', 'museum', 2, 2, 1, 2, 1, 3, 2),
  ('Art Gallery', 'art gallery', 'art_gallery', 1, 2, 1, 2, 1, 2, 2),
  ('Zoo', 'zoo', 'zoo', 3, 2, 1, 3, 4, 4, 2),
  ('Aquarium', 'aquarium', 'aquarium', 3, 2, 1, 3, 1, 3, 2),
  ('Botanical Garden', 'botanical garden', 'park', 2, 2, 1, 2, 5, 3, 2),
  ('Historical Walking Tour', 'historical walking tour', 'tourist_attraction', 2, 2, 1, 3, 4, 2, 2),
  ('Science Center', 'science museum', 'museum', 3, 2, 1, 3, 1, 3, 2),
  ('Planetarium', 'planetarium', 'museum', 2, 1, 1, 3, 1, 2, 3),
  ('Board Game Cafe', 'board game cafe', 'cafe', 2, 1, 3, 3, 1, 3, 2),
  ('Arcade', 'arcade', 'amusement_park', 2, 2, 3, 3, 1, 2, 1),
  ('Billiards / Pool Hall', 'pool hall billiards', 'bar', 2, 1, 3, 2, 1, 2, 1),
  ('Darts at a Bar', 'bar with darts', 'bar', 2, 1, 3, 3, 1, 2, 1),
  ('VR Experience', 'virtual reality experience', NULL, 3, 2, 2, 2, 1, 2, 4),
  ('Murder Mystery Dinner', 'murder mystery dinner', 'restaurant', 4, 1, 2, 4, 1, 3, 4),
  ('Spa Day', 'day spa', 'spa', 5, 1, 1, 2, 1, 4, 2),
  ('Yoga Class', 'yoga studio', 'gym', 2, 3, 1, 3, 2, 2, 1),
  ('Hot Spring / Bathhouse', 'hot spring bathhouse', 'spa', 3, 1, 1, 2, 3, 3, 3),
  ('Rage Room', 'rage room smash room', NULL, 3, 3, 1, 2, 1, 1, 5),
  ('Aerial Silks / Trapeze Class', 'aerial silks trapeze class', 'gym', 4, 5, 1, 2, 1, 2, 5),
  ('Archery Tag', 'archery tag', NULL, 3, 3, 5, 4, 2, 2, 4),
  ('Dance Class', 'dance class studio', NULL, 2, 3, 1, 3, 1, 2, 2),
  ('Salsa / Latin Dancing', 'salsa dancing class', NULL, 2, 3, 1, 4, 1, 2, 3),
  ('Amusement Park', 'amusement park', 'amusement_park', 4, 3, 1, 4, 4, 5, 2),
  ('Water Park', 'water park', 'amusement_park', 4, 3, 1, 4, 5, 5, 2),
  ('Mini Motorsports / Karting', 'karting track', NULL, 3, 2, 4, 3, 3, 2, 3),
  ('Horseback Riding', 'horseback riding trail', NULL, 4, 2, 1, 2, 5, 3, 4),
  ('Zip Lining', 'zip line adventure', NULL, 4, 3, 1, 3, 5, 3, 4),
  ('Whale Watching / Boat Tour', 'whale watching boat tour', NULL, 4, 1, 1, 4, 5, 4, 4),
  ('Improv / Comedy Workshop', 'improv comedy class', NULL, 3, 1, 1, 4, 1, 2, 4),
  ('Bouldering', 'bouldering gym', 'gym', 3, 5, 2, 2, 1, 3, 3),
  ('Surfing Lesson', 'surf lesson', NULL, 4, 4, 1, 2, 5, 3, 4),
  ('Fencing Class', 'fencing class', NULL, 3, 3, 4, 2, 1, 2, 5),
  ('Ax Throwing League Night', 'axe throwing league', NULL, 3, 2, 4, 4, 1, 3, 4),
  ('Night Market', 'night market', NULL, 2, 2, 1, 4, 5, 2, 3),
  ('Farmers Market', 'farmers market', NULL, 2, 2, 1, 3, 5, 2, 1),
  ('Escape Room (Horror)', 'horror escape room', NULL, 3, 2, 1, 3, 1, 2, 5);
