/** Maps each activity name to a representative emoji, shown on Swipe and Recommendation cards. */
export const ACTIVITY_ICONS: Record<string, string> = {
  "Hiking": "🥾",
  "Rock Climbing (Outdoor)": "🧗",
  "Kayaking": "🛶",
  "Beach Day": "🏖️",
  "Disc Golf": "🥏",
  "Picnic in the Park": "🧺",
  "Cycling": "🚴",
  "Stargazing": "🔭",
  "Camping": "⛺",
  "Paddleboarding": "🏄",
  "Bowling": "🎳",
  "Mini Golf": "⛳",
  "Go-Kart Racing": "🏎️",
  "Laser Tag": "🔫",
  "Rock Climbing (Indoor)": "🧗",
  "Paintball": "🎯",
  "Trampoline Park": "🤸",
  "Axe Throwing": "🪓",
  "Archery": "🏹",
  "Ice Skating": "⛸️",
  "Roller Skating": "🛼",
  "Batting Cages": "⚾",
  "Tennis": "🎾",
  "Volleyball": "🏐",
  "Basketball": "🏀",
  "Escape Room": "🔐",
  "Movie Theater": "🎬",
  "Trivia Night": "🧠",
  "Karaoke": "🎤",
  "Comedy Club": "🎭",
  "Live Music / Concert": "🎸",
  "Theater / Play": "🎭",
  "Haunted House": "👻",
  "Pottery Class": "🏺",
  "Sip and Paint": "🎨",
  "Cooking Class": "👨‍🍳",
  "Glassblowing Class": "🫧",
  "Photography Walk": "📷",
  "Craft Workshop": "✂️",
  "Candle Making Class": "🕯️",
  "Wine Tasting": "🍷",
  "Brewery Tour": "🍺",
  "Food Tour": "🍜",
  "Cocktail Making Class": "🍸",
  "Coffee Tasting": "☕",
  "Museum Visit": "🏛️",
  "Art Gallery": "🖼️",
  "Zoo": "🦁",
  "Aquarium": "🐠",
  "Botanical Garden": "🌸",
  "Historical Walking Tour": "🗺️",
  "Science Center": "🔬",
  "Planetarium": "🪐",
  "Board Game Cafe": "🎲",
  "Arcade": "🕹️",
  "Billiards / Pool Hall": "🎱",
  "Darts at a Bar": "🎯",
  "VR Experience": "🥽",
  "Murder Mystery Dinner": "🕵️",
  "Spa Day": "💆",
  "Yoga Class": "🧘",
  "Hot Spring / Bathhouse": "♨️",
  "Rage Room": "💥",
  "Aerial Silks / Trapeze Class": "🎪",
  "Archery Tag": "🏹",
  "Dance Class": "💃",
  "Salsa / Latin Dancing": "🪩",
  "Amusement Park": "🎡",
  "Water Park": "🌊",
  "Mini Motorsports / Karting": "🏁",
  "Horseback Riding": "🐴",
  "Zip Lining": "🪂",
  "Whale Watching / Boat Tour": "🐋",
  "Improv / Comedy Workshop": "🎭",
  "Bouldering": "🧗",
  "Surfing Lesson": "🏄",
  "Fencing Class": "🤺",
  "Ax Throwing League Night": "🪓",
  "Night Market": "🏮",
  "Farmers Market": "🥦",
  "Escape Room (Horror)": "😱",
};

export function getActivityIcon(name: string): string {
  return ACTIVITY_ICONS[name] ?? "🎉";
}
